services:
  - type: web
    name: shappno-vps
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class sync --workers 2 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: PLATFORM
        value: render
    healthCheckPath: /api/health
    autoDeploy: true